--PACKAGE PAQUETE_MUTANTE;
DROP PACKAGE PAQUETE_MUTANTE;

CREATE OR REPLACE PACKAGE PAQUETE_MUTANTE  AS
SUELDOJUGADOR JUGADOR.SUELDO%TYPE :=NULL;
PRESUPUESTOEQUIPO EQUIPO.PRESUPUESTO%TYPE :=NULL;
CODIGOEQUIPO JUGADOR.EQUIPO_ID_EQUIPO%TYPE :=NULL;
END;

CREATE OR REPLACE PACKAGE BODY PAQUETE_MUTANTE AS


--TRIGGER MUTANTE JUGADOR;
DROP TRIGGER TRIGGER_MUTANTE;

CREATE OR REPLACE TRIGGER TRIGGER_MUTANTE
AFTER INSERT OR UPDATE ON JUGADOR
FOR EACH ROW
BEGIN 
    PAQUETE_MUTANTE.CODIGOEQUIPO := :NEW.EQUIPO_ID_EQUIPO;
    PAQUETE_MUTANTE.SUELDOJUGADOR := :NEW.SUELDO;
END;

--TRIGGER MUTANTE EQUIPO

CREATE OR REPLACE TRIGGER TRIGGER_MUTANTE_EQUIPO
AFTER INSERT OR UPDATE ON EQUIPO
FOR EACH ROW
BEGIN 
    PAQUETE_MUTANTE.PRESUPUESTOEQUIPO := :NEW.PRESUPUESTO;
END;


--TRIGGER PRESUPUESTO EQUIPO

CREATE OR REPLACE TRIGGER MAX_PRESUPUESTO_EQUIPO
AFTER INSERT OR UPDATE ON EQUIPO
FOR EACH ROW
DECLARE
v_max_presupuesto NUMBER(6) := 200000;
BEGIN
    IF(PAQUETE_MUTANTE.PRESUPUESTOEQUIPO >= v_max_presupuesto) THEN
        raise_application_error(-20002, 'El presupuesto del equipo no puede ser superior a 200k');
    END IF;  
END MAX_PRESUPUESTO_EQUIPO; 



--TRIGGER SALARIO_MIN_JUGADOR

CREATE OR REPLACE TRIGGER SALARIO_MIN_JUGADOR
AFTER INSERT OR UPDATE ON Jugador
DECLARE
v_smi NUMBER(4) := 900;
BEGIN
    IF(PAQUETE_MUTANTE.SUELDOJUGADOR <= v_smi) THEN
        raise_application_error(-20001, 'El salario del jugador debe ser superior al SMI');
    END IF;  
END SALARIO_MIN_JUGADOR;

INSERT INTO JUGADOR VALUES(334, 'fsdf', 'fsdf', 'fsdfsdf', 'dfsff', 1800, 1, 1);

SELECT COUNT(*) FROM JUGADOR WHERE equipo_id_equipo = 1;
DELETE FROM JUGADOR WHERE EQUIPO_ID_EQUIPO = 1;

SELECT * FROM JUGADOR;


--TRIGGER MAX 6 JUGADORES

CREATE OR REPLACE TRIGGER MAX_JUGADOR
BEFORE INSERT OR UPDATE ON Jugador
FOR EACH ROW
DECLARE
v_max_jugadores NUMBER(1) := 6;
v_count_jugadores NUMBER(3);
BEGIN
    SELECT COUNT(*) AS "NUMERO JUGADORES" INTO v_count_jugadores FROM jugador
    WHERE equipo_id_equipo = (PAQUETE_MUTANTE.CODIGOEQUIPO);
    IF(v_count_jugadores >= v_max_jugadores) THEN
        raise_application_error(-20000, 'El numero de jugadores por equipo no puede ser superior a 6');
    END IF;  
END MAX_JUGADOR;

INSERT INTO JUGADOR VALUES(seq_jugador.nextval, 'sdffds', 'fsdfs', 'fsdf', 'sdfsdfdsf', 423234, 1, 10);
ROLLBACK;
select * from jugador where equipo_id_equipo = 10;
DELETE FROM JUGADOR WHERE ID_JUGADOR = 35;

