--PACKAGE PAQUETE_MUTANTE;

CREATE OR REPLACE PACKAGE PAQUETE_MUTANTE  AS
SUELDOJUGADOR JUGADOR.SUELDO%TYPE :=NULL;
PRESUPUESTOEQUIPO EQUIPO.PRESUPUESTO%TYPE :=NULL;
CODIGOEQUIPO JUGADOR.EQUIPO_ID_EQUIPO%TYPE :=NULL;
END;

--TRIGGER MUTANTE JUGADOR;

CREATE OR REPLACE TRIGGER TRIGGER_MUTANTE
AFTER INSERT OR UPDATE ON JUGADOR
FOR EACH ROW
BEGIN 
    PAQUETE_MUTANTE.CODIGOEQUIPO := :NEW.EQUIPO_ID_EQUIPO;
    PAQUETE_MUTANTE.SUELDOJUGADOR := :NEW.SUELDO;
END;

--TRIGGER MUTANTE EQUIPO

CREATE OR REPLACE TRIGGER TRIGGER_MUTANTE_EQUIPO
AFTER INSERT OR UPDATE ON EQUIPO
FOR EACH ROW
BEGIN 
    PAQUETE_MUTANTE.PRESUPUESTOEQUIPO := :NEW.PRESUPUESTO;
END;


--TRIGGER PRESUPUESTO EQUIPO

CREATE OR REPLACE TRIGGER MAX_PRESUPUESTO_EQUIPO
AFTER INSERT OR UPDATE ON EQUIPO
FOR EACH ROW
DECLARE
v_max_presupuesto NUMBER(6) := 200000;
BEGIN
    IF(PAQUETE_MUTANTE.PRESUPUESTOEQUIPO >= v_max_presupuesto) THEN
        raise_application_error(-20002, 'El presupuesto del equipo no puede ser superior a 200k');
    END IF;  
END MAX_PRESUPUESTO_EQUIPO; 


INSERT INTO EQUIPO VALUES(9, 'FSDF', 235523, 0);

SELECT * FROM EQUIPO;



--TRIGGER SALARIO_MIN_JUGADOR

CREATE OR REPLACE TRIGGER SALARIO_MIN_JUGADOR
BEFORE INSERT OR UPDATE ON Jugador
FOR EACH ROW
DECLARE
v_smi NUMBER(4) := 900;
BEGIN
    IF(PAQUETE_MUTANTE.SUELDOJUGADOR <= v_smi) THEN
        raise_application_error(-20001, 'El salario del jugador debe ser superior al SMI');
    END IF;  
END SALARIO_MIN_JUGADOR;

