DROP PACKAGE PAQUETE_MUTANTE;

CREATE OR REPLACE PACKAGE PAQUETE_MUTANTE  AS
SUELDOJUGADOR JUGADOR.SUELDO%TYPE :=NULL;
PRESUPUESTOEQUIPO EQUIPO.PRESUPUESTO%TYPE :=NULL;
CODIGOEQUIPO JUGADOR.EQUIPO_ID_EQUIPO%TYPE :=NULL;
END;