/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import main.MainEsports;
import modelo.Sesion;
import java.applet.AudioClip;

/**
 *
 * @author 1gdaw03
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static Sesion oSesion;
    private static AudioClip sonido;
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/music/bso.wav"));
        sonido.play();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        tfNombre = new javax.swing.JTextField();
        bEntrar = new javax.swing.JButton();
        bRegistrarUsuario = new javax.swing.JButton();
        bMusic = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pFondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgLogin/Mamecorp White.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 250, 210);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 250, 137, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 340, 85, 17);

        tfPassword.setBorder(null);
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(70, 370, 210, 30);

        tfNombre.setBorder(null);
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(tfNombre);
        tfNombre.setBounds(70, 280, 210, 30);

        bEntrar.setText("ENTRAR");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(bEntrar);
        bEntrar.setBounds(200, 430, 80, 23);

        bRegistrarUsuario.setBackground(new java.awt.Color(0, 0, 0));
        bRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrarUsuario.setText("¿Aún no tienes cuenta?");
        bRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bRegistrarUsuario);
        bRegistrarUsuario.setBounds(70, 510, 210, 23);

        bMusic.setBackground(new java.awt.Color(0, 0, 0));
        bMusic.setOpaque(false);
        bMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMusicActionPerformed(evt);
            }
        });
        getContentPane().add(bMusic);
        bMusic.setBounds(1080, 540, 33, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Silenciar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1020, 546, 70, 20);

        pFondoLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pFondoLogin.setForeground(new java.awt.Color(255, 255, 255));
        pFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgLogin/fondologin (2).jpg"))); // NOI18N
        getContentPane().add(pFondoLogin);
        pFondoLogin.setBounds(-220, -70, 1350, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void bRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarUsuarioActionPerformed
        /**
         * Al hacer click en este botón, abrimos el formulario para crear usuarios
         */
        ControladorVista.mostrarVentanaRegistroUsuarios();
        this.dispose();
    }//GEN-LAST:event_bRegistrarUsuarioActionPerformed

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        try {
            /**
             * Si el usuario hace click en este botón  el programa comprueba que
             * el usuario y la contraseña tecleadas existen en la base de datos.
             */
            
            oSesion = MainEsports.comprobarLogin(tfNombre.getText(),String.valueOf(tfPassword.getPassword()));
           
            if(oSesion == null){
                JOptionPane.showMessageDialog(this,"Usuario o contraseña incorrectos");
            }else{
                if(oSesion.getTipoUsuario().equals("admin")){
                    this.dispose();
                    ControladorVista.mostrarVentanaCategoria();
                }else{
                    this.dispose();
                    ControladorVista.mostrarVentanaUsuarios();
                }
            }
        } catch (Exception ex) {
            System.out.println(ex.getClass() + ex.getMessage());
            
        }
    }//GEN-LAST:event_bEntrarActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void bMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMusicActionPerformed
        // TODO add your handling code here:
        sonido.stop();

    }//GEN-LAST:event_bMusicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bMusic;
    private javax.swing.JButton bRegistrarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel pFondoLogin;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
