/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import javax.swing.JFrame;
import main.MainEsports;


/**
 *
 * @author PETO
 */
public class VentanaLiga extends javax.swing.JFrame {

    private static String operacion;
    /**
     * Creates new form VentanaInsertarLiga
     */
    public VentanaLiga(String operacionActiva) {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(rootPaneCheckingEnabled);
        setExtendedState(MAXIMIZED_BOTH);
        panelOpaco.setBackground(new Color(39,43,57,190));
        operacion = operacionActiva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpaco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel9 = new javax.swing.JLabel();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        bInsertar = new javax.swing.JButton();
        lFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        miVolver = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelOpaco.setLayout(null);

        jLabel1.setText("LIGA");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.add(jLabel1);
        jLabel1.setBounds(130, 280, 170, 120);

        jLabel6.setText("NOMBRE DE LIGA");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.add(jLabel6);
        jLabel6.setBounds(10, 420, 150, 17);
        panelOpaco.add(jTextField3);
        jTextField3.setBounds(170, 420, 190, 20);

        jLabel8.setText("FECHA DE INICIO");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.add(jLabel8);
        jLabel8.setBounds(10, 470, 140, 17);
        panelOpaco.add(datePicker1);
        datePicker1.setBounds(170, 470, 190, 20);

        jLabel9.setText("FECHA DE FIN");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.add(jLabel9);
        jLabel9.setBounds(10, 520, 170, 17);
        panelOpaco.add(datePicker2);
        datePicker2.setBounds(170, 520, 190, 20);

        jLabel5.setText("LIGA EN CURSO");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.add(jLabel5);
        jLabel5.setBounds(10, 580, 130, 17);
        panelOpaco.add(jCheckBox1);
        jCheckBox1.setBounds(170, 580, 30, 21);

        bInsertar.setText("ACEPTAR");
        bInsertar.setBackground(new java.awt.Color(0, 40, 135));
        bInsertar.setBorder(null);
        bInsertar.setBorderPainted(false);
        bInsertar.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.add(bInsertar);
        bInsertar.setBounds(260, 623, 100, 30);

        getContentPane().add(panelOpaco);
        panelOpaco.setBounds(0, -230, 400, 1430);

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgLiga/LigaFondo.jpg"))); // NOI18N
        getContentPane().add(lFondo);
        lFondo.setBounds(-320, -250, 2560, 1440);

        miVolver.setText("Volver");
        miVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miVolverMouseClicked(evt);
            }
        });
        jMenuBar1.add(miVolver);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miVolverMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ControladorVista.mostrarVentanaCategoria();
    }//GEN-LAST:event_miVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      

      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInsertar;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lFondo;
    private javax.swing.JMenu miVolver;
    private javax.swing.JPanel panelOpaco;
    // End of variables declaration//GEN-END:variables
}
