/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.MainEsports;
import modelo.Equipo;

/**
 *
 * @author 1gdaw03
 */
public class VentanaVisualizarLiga extends javax.swing.JFrame {
    
    private static ArrayList<Equipo> listaEquipos;
    /**
     * Creates new form VentanaVisualizarLiga
     */
    public VentanaVisualizarLiga() throws Exception {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(rootPaneCheckingEnabled);
        setExtendedState(MAXIMIZED_BOTH);
        panelOpaco.setBackground(new Color(39, 118, 173,190));
        getClasificacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelOpaco = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lEquipo1 = new javax.swing.JLabel();
        lEquipo3 = new javax.swing.JLabel();
        lEquipo2 = new javax.swing.JLabel();
        lEquipo4 = new javax.swing.JLabel();
        lEquipo5 = new javax.swing.JLabel();
        lEquipo6 = new javax.swing.JLabel();
        lPuntos1 = new javax.swing.JLabel();
        lPuntos2 = new javax.swing.JLabel();
        lPuntos4 = new javax.swing.JLabel();
        lPuntos3 = new javax.swing.JLabel();
        lPuntos5 = new javax.swing.JLabel();
        lPuntos6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RANKING");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("POSICION");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PUNTOS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EQUIPO");

        bVolver.setBackground(new java.awt.Color(255, 255, 255));
        bVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgLiga/icon1.png"))); // NOI18N
        bVolver.setBorderPainted(false);
        bVolver.setContentAreaFilled(false);
        bVolver.setFocusPainted(false);
        bVolver.setRequestFocusEnabled(false);
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("1");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("5");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("6");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lEquipo1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lEquipo1.setForeground(new java.awt.Color(255, 255, 255));
        lEquipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipo1.setText("unknown");
        lEquipo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lEquipo3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lEquipo3.setForeground(new java.awt.Color(255, 255, 255));
        lEquipo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipo3.setText("unknown");
        lEquipo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lEquipo2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lEquipo2.setForeground(new java.awt.Color(255, 255, 255));
        lEquipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipo2.setText("unknown");
        lEquipo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lEquipo4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lEquipo4.setForeground(new java.awt.Color(255, 255, 255));
        lEquipo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipo4.setText("unknown");
        lEquipo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lEquipo5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lEquipo5.setForeground(new java.awt.Color(255, 255, 255));
        lEquipo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipo5.setText("unknown");
        lEquipo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lEquipo6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lEquipo6.setForeground(new java.awt.Color(255, 255, 255));
        lEquipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipo6.setText("unknown");
        lEquipo6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPuntos1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPuntos1.setForeground(new java.awt.Color(255, 255, 255));
        lPuntos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntos1.setText("unknown");
        lPuntos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPuntos2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPuntos2.setForeground(new java.awt.Color(255, 255, 255));
        lPuntos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntos2.setText("unknown");
        lPuntos2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPuntos4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPuntos4.setForeground(new java.awt.Color(255, 255, 255));
        lPuntos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntos4.setText("unknown");
        lPuntos4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPuntos3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPuntos3.setForeground(new java.awt.Color(255, 255, 255));
        lPuntos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntos3.setText("unknown");
        lPuntos3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPuntos5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPuntos5.setForeground(new java.awt.Color(255, 255, 255));
        lPuntos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntos5.setText("unknown");
        lPuntos5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPuntos6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPuntos6.setForeground(new java.awt.Color(255, 255, 255));
        lPuntos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntos6.setText("unknown");
        lPuntos6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelOpacoLayout = new javax.swing.GroupLayout(panelOpaco);
        panelOpaco.setLayout(panelOpacoLayout);
        panelOpacoLayout.setHorizontalGroup(
            panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpacoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpacoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEquipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEquipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEquipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEquipo6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPuntos1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(lPuntos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPuntos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPuntos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPuntos5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPuntos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOpacoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpacoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelOpacoLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpacoLayout.setVerticalGroup(
            panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPuntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPuntos2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEquipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPuntos3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEquipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPuntos4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEquipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPuntos5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEquipo6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPuntos6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(bVolver)
                .addContainerGap())
        );

        getContentPane().add(panelOpaco);
        panelOpaco.setBounds(660, 180, 610, 700);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgLiga/FondoClasificacion.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1950, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ControladorVista.OcultarVentanaVisualizarLiga();
        ControladorVista.mostrarVentanaUsuarios();
    }//GEN-LAST:event_bVolverActionPerformed
    
    private void getClasificacion() throws Exception{
        listaEquipos = MainEsports.getClasificacion();
        
        if(listaEquipos != null){
            lEquipo1.setText(listaEquipos.get(0).getNombre().toUpperCase());
            lPuntos1.setText(String.valueOf(listaEquipos.get(0).getPuntos()));
            lEquipo2.setText(listaEquipos.get(1).getNombre().toUpperCase());
            lPuntos2.setText(String.valueOf(listaEquipos.get(1).getPuntos()));
            lEquipo3.setText(listaEquipos.get(2).getNombre().toUpperCase());
            lPuntos3.setText(String.valueOf(listaEquipos.get(2).getPuntos()));
            lEquipo4.setText(listaEquipos.get(3).getNombre().toUpperCase());
            lPuntos4.setText(String.valueOf(listaEquipos.get(3).getPuntos()));
            lEquipo5.setText(listaEquipos.get(4).getNombre().toUpperCase());
            lPuntos5.setText(String.valueOf(listaEquipos.get(4).getPuntos()));
            lEquipo6.setText(listaEquipos.get(5).getNombre().toUpperCase());
            lPuntos6.setText(String.valueOf(listaEquipos.get(5).getPuntos()));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaVisualizarLiga().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaVisualizarLiga.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lEquipo1;
    private javax.swing.JLabel lEquipo2;
    private javax.swing.JLabel lEquipo3;
    private javax.swing.JLabel lEquipo4;
    private javax.swing.JLabel lEquipo5;
    private javax.swing.JLabel lEquipo6;
    private javax.swing.JLabel lPuntos1;
    private javax.swing.JLabel lPuntos2;
    private javax.swing.JLabel lPuntos3;
    private javax.swing.JLabel lPuntos4;
    private javax.swing.JLabel lPuntos5;
    private javax.swing.JLabel lPuntos6;
    private javax.swing.JPanel panelOpaco;
    // End of variables declaration//GEN-END:variables
}
