package vistas;

import java.awt.ComponentOrientation;

/**
 *
 * @author N3Essential
 */
public class VentanaCategoria extends javax.swing.JFrame {

    
    /**
     * Creates new form VentanaCategoria
     */
    public VentanaCategoria() {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(rootPaneCheckingEnabled);
        setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bModulos = new javax.swing.JButton();
        bPuestos = new javax.swing.JButton();
        bIngenieros = new javax.swing.JButton();
        bMisiones = new javax.swing.JButton();
        bTipos1 = new javax.swing.JButton();
        bPresidente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCategoria = new javax.swing.JMenu();
        miTipos = new javax.swing.JMenuItem();
        miModulos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        miMisiones = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Light", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Mamecorp logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 340, 630, 350));

        bModulos.setBackground(new java.awt.Color(0, 102, 102));
        bModulos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bModulos.setForeground(new java.awt.Color(255, 255, 255));
        bModulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Jornada.png"))); // NOI18N
        bModulos.setText("   JORNADAS");
        bModulos.setBorder(null);
        bModulos.setBorderPainted(false);
        bModulos.setContentAreaFilled(false);
        bModulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModulos.setFocusPainted(false);
        bModulos.setOpaque(false);
        bModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModulosActionPerformed(evt);
            }
        });
        getContentPane().add(bModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, 50));

        bPuestos.setBackground(new java.awt.Color(0, 102, 102));
        bPuestos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bPuestos.setForeground(new java.awt.Color(255, 255, 255));
        bPuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Equipo.png"))); // NOI18N
        bPuestos.setText("    EQUIPOS");
        bPuestos.setBorder(null);
        bPuestos.setContentAreaFilled(false);
        bPuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPuestos.setFocusPainted(false);
        bPuestos.setOpaque(false);
        bPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuestosActionPerformed(evt);
            }
        });
        getContentPane().add(bPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 260, 70));

        bIngenieros.setBackground(new java.awt.Color(0, 102, 102));
        bIngenieros.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bIngenieros.setForeground(new java.awt.Color(255, 255, 255));
        bIngenieros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/JugadorEsports.png"))); // NOI18N
        bIngenieros.setText("   JUGADORES");
        bIngenieros.setBorder(null);
        bIngenieros.setContentAreaFilled(false);
        bIngenieros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bIngenieros.setFocusPainted(false);
        bIngenieros.setOpaque(false);
        bIngenieros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngenierosActionPerformed(evt);
            }
        });
        getContentPane().add(bIngenieros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 260, 50));

        bMisiones.setBackground(new java.awt.Color(0, 102, 102));
        bMisiones.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bMisiones.setForeground(new java.awt.Color(255, 255, 255));
        bMisiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Partido.png"))); // NOI18N
        bMisiones.setText("    PARTIDOS");
        bMisiones.setBorder(null);
        bMisiones.setContentAreaFilled(false);
        bMisiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bMisiones.setFocusPainted(false);
        bMisiones.setOpaque(false);
        bMisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMisionesActionPerformed(evt);
            }
        });
        getContentPane().add(bMisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 230, 60));

        bTipos1.setBackground(new java.awt.Color(255, 255, 255));
        bTipos1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bTipos1.setForeground(new java.awt.Color(255, 255, 255));
        bTipos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Icono liga.png"))); // NOI18N
        bTipos1.setText("        LIGA");
        bTipos1.setBorder(null);
        bTipos1.setContentAreaFilled(false);
        bTipos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTipos1.setFocusPainted(false);
        bTipos1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bTipos1MouseMoved(evt);
            }
        });
        bTipos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTipos1ActionPerformed(evt);
            }
        });
        getContentPane().add(bTipos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, 60));

        bPresidente.setBackground(new java.awt.Color(0, 102, 102));
        bPresidente.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bPresidente.setForeground(new java.awt.Color(255, 255, 255));
        bPresidente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Presidentes.png"))); // NOI18N
        bPresidente.setText("  PRESIDENTES");
        bPresidente.setBorder(null);
        bPresidente.setContentAreaFilled(false);
        bPresidente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPresidente.setFocusPainted(false);
        bPresidente.setOpaque(false);
        bPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPresidenteActionPerformed(evt);
            }
        });
        getContentPane().add(bPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 290, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/FondoCategoria.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -630, 3500, 2650));

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenuCategoria.setText("Categoria");
        jMenuCategoria.setBorderPainted(false);

        miTipos.setText("Liga");
        miTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miTiposMouseClicked(evt);
            }
        });
        miTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTiposActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miTipos);

        miModulos.setText("Jornadas");
        miModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModulosActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miModulos);

        jMenuItem2.setText("Partidos");
        jMenuCategoria.add(jMenuItem2);

        jMenuItem3.setText("Equipos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuCategoria.add(jMenuItem3);

        jMenuItem4.setText("Jugadores");
        jMenuCategoria.add(jMenuItem4);

        jMenuItem1.setText("Presidentes");
        jMenuCategoria.add(jMenuItem1);

        jMenuBar1.add(jMenuCategoria);

        miMisiones.setText("Cuentas");
        miMisiones.setBorderPainted(false);
        miMisiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miMisionesMouseClicked(evt);
            }
        });

        jMenuItem6.setText("Administradores");
        miMisiones.add(jMenuItem6);

        jMenuItem5.setText("Usuarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        miMisiones.add(jMenuItem5);

        jMenuBar1.add(miMisiones);

        miSalir.setText("Salir");
        miSalir.setBorderPainted(false);
        miSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        miSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miSalir.setInheritsPopupMenu(true);
        miSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(miSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModulosActionPerformed
        
    }//GEN-LAST:event_bModulosActionPerformed

    private void bMisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMisionesActionPerformed
        
    }//GEN-LAST:event_bMisionesActionPerformed

    private void bPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuestosActionPerformed
       
    }//GEN-LAST:event_bPuestosActionPerformed

    private void bIngenierosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngenierosActionPerformed
        
    }//GEN-LAST:event_bIngenierosActionPerformed

    private void miSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miSalirMouseClicked
       System.exit(0);
    }//GEN-LAST:event_miSalirMouseClicked

    private void miTiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miTiposMouseClicked
  
    }//GEN-LAST:event_miTiposMouseClicked

    private void miTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTiposActionPerformed

    }//GEN-LAST:event_miTiposActionPerformed

    private void miModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModulosActionPerformed
        
    }//GEN-LAST:event_miModulosActionPerformed

    private void miMisionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miMisionesMouseClicked
        
    }//GEN-LAST:event_miMisionesMouseClicked

    private void bTipos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTipos1ActionPerformed
        
    }//GEN-LAST:event_bTipos1ActionPerformed

    private void bPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPresidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPresidenteActionPerformed

    private void bTipos1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTipos1MouseMoved
   
    }//GEN-LAST:event_bTipos1MouseMoved

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngenieros;
    private javax.swing.JButton bMisiones;
    private javax.swing.JButton bModulos;
    private javax.swing.JButton bPresidente;
    private javax.swing.JButton bPuestos;
    private javax.swing.JButton bTipos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCategoria;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu miMisiones;
    private javax.swing.JMenuItem miModulos;
    private javax.swing.JMenu miSalir;
    private javax.swing.JMenuItem miTipos;
    // End of variables declaration//GEN-END:variables
}
