/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import main.MainEsports;
import modelo.Jornada;
import modelo.Partido;

/**
 *
 * @author 1gdaw03
 */
public class VentanaVisualizarJornada extends javax.swing.JFrame {
    

    private static ArrayList<Partido> listaPartidos;
    private static ArrayList<Jornada> listaJornadas;
    
    /**
     * Creates new form VentanaVisualizarJornada
     * @throws java.lang.Exception
     */
    public VentanaVisualizarJornada() throws Exception {
        //setUndecorated(true);
        initComponents();
        //setAlwaysOnTop(rootPaneCheckingEnabled);
       //setExtendedState(MAXIMIZED_BOTH);
        panelOpaco.setBackground(new Color(39, 118, 173,150));
        llenarComboBoxJornadas();
        consultarPartidosDeCadaJornada();
        setDatosPrimeraJornada();
    }
    
    public final void llenarComboBoxJornadas() throws Exception{
        listaJornadas = MainEsports.consultarJornadas(); 
                
        //Llenamos la combo box
        for(int i = 0; i < listaJornadas.size(); i++){
            cbJornada.addItem("Jornada " + listaJornadas.get(i).getIdJornada());
        }
    }
    
    public final void consultarPartidosDeCadaJornada() throws Exception{
        listaJornadas = MainEsports.consultarPartidosDeCadaJornada();
    }
    
    public final void setDatosPrimeraJornada() throws Exception{
        tfEquipoLocal1.setText(listaJornadas.get(0).getListaPartidos().get(0).getEquipoLocal().getNombre().toUpperCase());
        tfEquipoLocal2.setText(listaJornadas.get(0).getListaPartidos().get(1).getEquipoLocal().getNombre().toUpperCase());
        tfEquipoLocal3.setText(listaJornadas.get(0).getListaPartidos().get(2).getEquipoLocal().getNombre().toUpperCase());
        tfEquipoVisitante1.setText(listaJornadas.get(0).getListaPartidos().get(0).getEquipoVisitante().getNombre().toUpperCase());
        tfEquipoVisitante2.setText(listaJornadas.get(0).getListaPartidos().get(1).getEquipoVisitante().getNombre().toUpperCase());
        tfEquipoVisitante3.setText(listaJornadas.get(0).getListaPartidos().get(2).getEquipoVisitante().getNombre().toUpperCase());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpaco = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbJornada = new javax.swing.JComboBox<>();
        bVolver = new javax.swing.JButton();
        bRefrescar = new javax.swing.JButton();
        tfEquipoLocal1 = new javax.swing.JLabel();
        tfEquipoLocal3 = new javax.swing.JLabel();
        tfEquipoVisitante1 = new javax.swing.JLabel();
        tfEquipoLocal2 = new javax.swing.JLabel();
        tfEquipoVisitante2 = new javax.swing.JLabel();
        tfEquipoVisitante3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgJornada/Versus_icon (1).png"))); // NOI18N

        cbJornada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJornadaActionPerformed(evt);
            }
        });

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        bRefrescar.setText("Refresh");
        bRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefrescarActionPerformed(evt);
            }
        });

        tfEquipoLocal1.setBackground(new java.awt.Color(153, 153, 255));
        tfEquipoLocal1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfEquipoLocal1.setForeground(new java.awt.Color(255, 255, 255));
        tfEquipoLocal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfEquipoLocal1.setText("jLabel3");
        tfEquipoLocal1.setOpaque(true);

        tfEquipoLocal3.setBackground(new java.awt.Color(153, 153, 255));
        tfEquipoLocal3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfEquipoLocal3.setForeground(new java.awt.Color(255, 255, 255));
        tfEquipoLocal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfEquipoLocal3.setText("jLabel3");
        tfEquipoLocal3.setOpaque(true);

        tfEquipoVisitante1.setBackground(new java.awt.Color(153, 153, 255));
        tfEquipoVisitante1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfEquipoVisitante1.setForeground(new java.awt.Color(255, 255, 255));
        tfEquipoVisitante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfEquipoVisitante1.setText("jLabel3");
        tfEquipoVisitante1.setOpaque(true);

        tfEquipoLocal2.setBackground(new java.awt.Color(153, 153, 255));
        tfEquipoLocal2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfEquipoLocal2.setForeground(new java.awt.Color(255, 255, 255));
        tfEquipoLocal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfEquipoLocal2.setText("jLabel3");
        tfEquipoLocal2.setOpaque(true);

        tfEquipoVisitante2.setBackground(new java.awt.Color(153, 153, 255));
        tfEquipoVisitante2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfEquipoVisitante2.setForeground(new java.awt.Color(255, 255, 255));
        tfEquipoVisitante2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfEquipoVisitante2.setText("jLabel3");
        tfEquipoVisitante2.setOpaque(true);

        tfEquipoVisitante3.setBackground(new java.awt.Color(153, 153, 255));
        tfEquipoVisitante3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfEquipoVisitante3.setForeground(new java.awt.Color(255, 255, 255));
        tfEquipoVisitante3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfEquipoVisitante3.setText("jLabel3");
        tfEquipoVisitante3.setOpaque(true);

        javax.swing.GroupLayout panelOpacoLayout = new javax.swing.GroupLayout(panelOpaco);
        panelOpaco.setLayout(panelOpacoLayout);
        panelOpacoLayout.setHorizontalGroup(
            panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacoLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpacoLayout.createSequentialGroup()
                        .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfEquipoLocal1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEquipoLocal3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEquipoLocal2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEquipoVisitante3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEquipoVisitante2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEquipoVisitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpacoLayout.createSequentialGroup()
                        .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(433, 433, 433))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpacoLayout.createSequentialGroup()
                        .addComponent(bVolver)
                        .addGap(493, 493, 493))))
            .addGroup(panelOpacoLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(bRefrescar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelOpacoLayout.setVerticalGroup(
            panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelOpacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpacoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRefrescar)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpacoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(tfEquipoLocal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEquipoLocal2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEquipoLocal3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpacoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(tfEquipoVisitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEquipoVisitante2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEquipoVisitante3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bVolver)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(panelOpaco);
        panelOpaco.setBounds(460, 290, 1060, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgJornada/FondoJornada_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 2050, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ControladorVista.OcultarVentanaVisualizarJornada();
        ControladorVista.mostrarVentanaUsuarios();
    }//GEN-LAST:event_bVolverActionPerformed

    private void bRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefrescarActionPerformed
        switch(cbJornada.getSelectedIndex()){
            case 0:
                tfEquipoLocal1.setText(listaJornadas.get(0).getListaPartidos().get(0).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoLocal2.setText(listaJornadas.get(0).getListaPartidos().get(1).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoLocal3.setText(listaJornadas.get(0).getListaPartidos().get(2).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoVisitante1.setText(listaJornadas.get(0).getListaPartidos().get(0).getEquipoVisitante().getNombre().toUpperCase());
                tfEquipoVisitante2.setText(listaJornadas.get(0).getListaPartidos().get(1).getEquipoVisitante().getNombre().toUpperCase());
                tfEquipoVisitante3.setText(listaJornadas.get(0).getListaPartidos().get(2).getEquipoVisitante().getNombre().toUpperCase());
            break;
            case 1:
                tfEquipoLocal1.setText(listaJornadas.get(1).getListaPartidos().get(0).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoLocal2.setText(listaJornadas.get(1).getListaPartidos().get(1).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoLocal3.setText(listaJornadas.get(1).getListaPartidos().get(2).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoVisitante1.setText(listaJornadas.get(1).getListaPartidos().get(0).getEquipoVisitante().getNombre().toUpperCase());
                tfEquipoVisitante2.setText(listaJornadas.get(1).getListaPartidos().get(1).getEquipoVisitante().getNombre().toUpperCase());
                tfEquipoVisitante3.setText(listaJornadas.get(1).getListaPartidos().get(2).getEquipoVisitante().getNombre().toUpperCase());
            break;
            case 2:
                tfEquipoLocal1.setText(listaJornadas.get(2).getListaPartidos().get(0).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoLocal2.setText(listaJornadas.get(2).getListaPartidos().get(1).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoLocal3.setText(listaJornadas.get(2).getListaPartidos().get(2).getEquipoLocal().getNombre().toUpperCase());
                tfEquipoVisitante1.setText(listaJornadas.get(2).getListaPartidos().get(0).getEquipoVisitante().getNombre().toUpperCase());
                tfEquipoVisitante2.setText(listaJornadas.get(2).getListaPartidos().get(1).getEquipoVisitante().getNombre().toUpperCase());
                tfEquipoVisitante3.setText(listaJornadas.get(2).getListaPartidos().get(2).getEquipoVisitante().getNombre().toUpperCase());
            break;
        }
    }//GEN-LAST:event_bRefrescarActionPerformed

    private void cbJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJornadaActionPerformed

    }//GEN-LAST:event_cbJornadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaVisualizarJornada().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaVisualizarJornada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRefrescar;
    private javax.swing.JButton bVolver;
    private javax.swing.JComboBox<String> cbJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelOpaco;
    private javax.swing.JLabel tfEquipoLocal1;
    private javax.swing.JLabel tfEquipoLocal2;
    private javax.swing.JLabel tfEquipoLocal3;
    private javax.swing.JLabel tfEquipoVisitante1;
    private javax.swing.JLabel tfEquipoVisitante2;
    private javax.swing.JLabel tfEquipoVisitante3;
    // End of variables declaration//GEN-END:variables
}
