/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.MainEsports;
import modelo.Equipo;

/**
 *
 * @author PETO
 */
public class VentanaEquipos extends javax.swing.JFrame {
    private String operacion;
    private static Equipo oEquipo;
    int modificar;
    String nombreEquipo;


    /**
     * Creates new form VentanaEquipos
     */
    public VentanaEquipos(String operacionActiva) throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        panelOpaco.setBackground(new Color(2,91,136,190));
        operacion = operacionActiva;
        if(operacion.equals("baja")){
             pedirEquipoABorrar();
        }
        if(operacion.equals("modificar")){
             pedirEquipoAModificar();
        }        
        
        //mostrarOocultarfields();
    }
    public VentanaEquipos(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpaco = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfPresupuesto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPuntos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bInsertar = new javax.swing.JButton();
        lFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        miVolver = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelOpaco.setForeground(new java.awt.Color(255, 255, 255));
        panelOpaco.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        panelOpaco.add(jLabel3);
        jLabel3.setBounds(20, 300, 100, 17);
        panelOpaco.add(tfNombre);
        tfNombre.setBounds(160, 300, 200, 20);
        panelOpaco.add(tfPresupuesto);
        tfPresupuesto.setBounds(160, 340, 200, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRESUPUESTO");
        panelOpaco.add(jLabel4);
        jLabel4.setBounds(20, 340, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PUNTOS");
        panelOpaco.add(jLabel5);
        jLabel5.setBounds(20, 380, 70, 17);
        panelOpaco.add(tfPuntos);
        tfPuntos.setBounds(160, 380, 200, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EQUIPO");
        panelOpaco.add(jLabel2);
        jLabel2.setBounds(100, 150, 340, 140);

        bInsertar.setBackground(new java.awt.Color(0, 40, 135));
        bInsertar.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bInsertar.setForeground(new java.awt.Color(255, 255, 255));
        bInsertar.setText("ACEPTAR");
        bInsertar.setBorder(null);
        bInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });
        panelOpaco.add(bInsertar);
        bInsertar.setBounds(260, 440, 100, 30);

        getContentPane().add(panelOpaco);
        panelOpaco.setBounds(0, -140, 400, 1310);

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgEquipo/EquipoFondo.png"))); // NOI18N
        lFondo.setText("jLabel6");
        getContentPane().add(lFondo);
        lFondo.setBounds(-380, -170, 2350, 1400);

        miVolver.setText("Volver");
        miVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miVolverMouseClicked(evt);
            }
        });
        jMenuBar1.add(miVolver);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void mostrarOocultarfields(){
       
       if(operacion.equals("baja")){
           
           tfNombre.setEnabled(false);
           tfPresupuesto.setEnabled(false);
           tfPuntos.setEnabled(false);
           tfNombre.setText(oEquipo.getNombre());
           tfPresupuesto.setText(String.valueOf(oEquipo.getPresupuesto()));
           tfPuntos.setText(String.valueOf(oEquipo.getPuntos()));
       }
       if(operacion.equals("modificar")){
           tfNombre.setText(oEquipo.getNombre());
           tfPresupuesto.setText(String.valueOf(oEquipo.getPresupuesto()));
           tfPuntos.setText(String.valueOf(oEquipo.getPuntos()));
           
       
       }    
       
   }
   
   public void pedirEquipoABorrar(){
    /**
    *  preguntamos al usuario que equipo quiere borrar y recogemos los datos
    */
        try{
            while(oEquipo == null){
                nombreEquipo = JOptionPane.showInputDialog(this, "¿Qué EQUIPO quieres BORRAR?");
                oEquipo = MainEsports.buscarEquipo(nombreEquipo);
            }
            
            ControladorVista.mostrarVentanaEquipos();
            mostrarOocultarfields();
            }catch(Exception E){
                System.out.println("Excepcion " + E.getClass() + E.getMessage());
            } 
    }
   
    public void pedirEquipoAModificar(){
    /**
    *  preguntamos al usuario que equipo quiere borrar y recogemos los datos
    */
        try{
            while(oEquipo == null){
                nombreEquipo = JOptionPane.showInputDialog("¿Qué EQUIPO quieres MODIFICAR?");
                oEquipo = MainEsports.buscarEquipo(nombreEquipo);
            }
            
            ControladorVista.mostrarVentanaEquipos();
            mostrarOocultarfields();
            }catch(Exception E){
                System.out.println("Excepcion " + E.getClass() + E.getMessage());
            } 
    }

    
    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarActionPerformed
        
        String nombre = tfNombre.getText();
        int presupuesto = Integer.parseInt(tfPresupuesto.getText());
        int puntos = Integer.parseInt(tfPuntos.getText());
        
        if(operacion.equals("alta")){
            try {

                int insercion= MainEsports.insertarEquipos(tfNombre.getText(),Integer.parseInt(tfPresupuesto.getText()),Integer.parseInt(tfPuntos.getText()));

                if(insercion > 0){
                    JOptionPane.showMessageDialog(this,"Linea insertada correctamente");
                    tfNombre.setText("");
                    tfPresupuesto.setText("");
                    tfPuntos.setText(""); 
                }else{
                    JOptionPane.showMessageDialog(this,"ERROR AL INSERTAR");
                }

            } catch (Exception ex) {
                System.out.println(ex.getClass() + ex.getMessage());
            }
        } 
        
        if(operacion.equals("modificar")){

           try {
               modificar = MainEsports.modificarEquipo(nombre,presupuesto,puntos);
           } catch (Exception ex) {
               System.out.println("Excepcion " + ex.getClass() + ex.getMessage());;
           }

             if(modificar >=1){
                 JOptionPane.showMessageDialog(this, "Equipo " + nombre + " actualizado");
             }else{
                 JOptionPane.showMessageDialog(this, "OOOPSS... Algo salió mal al actualizar");
             }


        }
        if(operacion.equals("baja")){

            try {
               int delete = MainEsports.borrarEquipo(nombre,presupuesto,puntos);
                if(delete == 1){
                    JOptionPane.showMessageDialog(this, "Equipo " + nombre + " borrado");
                }else{
                    JOptionPane.showMessageDialog(this, "OOOPSS... Algo salió mal al borrar");
                }
            } catch (Exception ex) {
               System.out.println("Excepcion " + ex.getClass() + ex.getMessage());;
            }

            
        }  
    }//GEN-LAST:event_bInsertarActionPerformed

    private void miVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miVolverMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ControladorVista.mostrarVentanaCategoria();
    }//GEN-LAST:event_miVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInsertar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lFondo;
    private javax.swing.JMenu miVolver;
    private javax.swing.JPanel panelOpaco;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPresupuesto;
    private javax.swing.JTextField tfPuntos;
    // End of variables declaration//GEN-END:variables
}
