package vistas;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author N3Essential
 */
public class VentanaUsuarios extends javax.swing.JFrame {
        
    private String operacionActiva;
    private String opcionActiva;
    
    /**
     * Creates new form VentanaCategoria
     */
    public VentanaUsuarios() {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(rootPaneCheckingEnabled);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bJornadas = new javax.swing.JButton();
        bEquipos = new javax.swing.JButton();
        bLiga = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCategoria = new javax.swing.JMenu();
        miLiga = new javax.swing.JMenuItem();
        miJornadas = new javax.swing.JMenuItem();
        miEquipos = new javax.swing.JMenuItem();
        jMenuVolver = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bJornadas.setBackground(new java.awt.Color(0, 102, 102));
        bJornadas.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bJornadas.setForeground(new java.awt.Color(255, 255, 255));
        bJornadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/imgVentanaCategoria/Jornada.png"))); // NOI18N
        bJornadas.setText("   JORNADAS");
        bJornadas.setBorder(null);
        bJornadas.setBorderPainted(false);
        bJornadas.setContentAreaFilled(false);
        bJornadas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bJornadas.setFocusPainted(false);
        bJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJornadasActionPerformed(evt);
            }
        });
        getContentPane().add(bJornadas);
        bJornadas.setBounds(320, 330, 230, 50);

        bEquipos.setBackground(new java.awt.Color(0, 102, 102));
        bEquipos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bEquipos.setForeground(new java.awt.Color(255, 255, 255));
        bEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/imgVentanaCategoria/Equipo.png"))); // NOI18N
        bEquipos.setText("    EQUIPOS");
        bEquipos.setBorder(null);
        bEquipos.setContentAreaFilled(false);
        bEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bEquipos.setFocusPainted(false);
        bEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(bEquipos);
        bEquipos.setBounds(300, 500, 260, 70);

        bLiga.setBackground(new java.awt.Color(255, 255, 255));
        bLiga.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bLiga.setForeground(new java.awt.Color(255, 255, 255));
        bLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/imgVentanaCategoria/Icono liga.png"))); // NOI18N
        bLiga.setText("        LIGA");
        bLiga.setBorder(null);
        bLiga.setContentAreaFilled(false);
        bLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bLiga.setFocusPainted(false);
        bLiga.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bLigaMouseMoved(evt);
            }
        });
        bLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLigaActionPerformed(evt);
            }
        });
        getContentPane().add(bLiga);
        bLiga.setBounds(320, 150, 190, 60);

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1760, 40, 100, 24);

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel3:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1638, 40, 110, 24);

        bLogOut.setText("Log Out!");
        bLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(bLogOut);
        bLogOut.setBounds(1750, 130, 75, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/imgVentanaCategoria/FondoCategoria.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-260, -630, 3500, 2650);

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenuCategoria.setText("Categoria");

        miLiga.setText("Liga");
        miLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLigaActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miLiga);

        miJornadas.setText("Jornadas");
        miJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJornadasActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miJornadas);

        miEquipos.setText("Equipos");
        miEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEquiposActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miEquipos);

        jMenuBar1.add(jMenuCategoria);

        jMenuVolver.setText("Volver");
        jMenuVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVolverMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVolver);

        jMenuSalir.setText("Salir");
        jMenuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuSalir.setInheritsPopupMenu(true);
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEquiposActionPerformed
       operacionActiva = "equipo";
       this.dispose();
        try {
            ControladorVista.mostrarVentanaVisualizarEquipos();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bEquiposActionPerformed

    private void miLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLigaActionPerformed
        bLiga.doClick();
    }//GEN-LAST:event_miLigaActionPerformed

    private void miJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJornadasActionPerformed
        bJornadas.doClick();
    }//GEN-LAST:event_miJornadasActionPerformed

    private void miEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEquiposActionPerformed
        bEquipos.doClick();
    }//GEN-LAST:event_miEquiposActionPerformed

    private void bLigaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLigaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_bLigaMouseMoved

    private void bLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLigaActionPerformed
       operacionActiva = "liga";
        try {
            ControladorVista.mostrarVentanaVisualizarLiga();   
           
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
         this.dispose();
   
    }//GEN-LAST:event_bLigaActionPerformed

    private void jMenuVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVolverMouseClicked
        showCategorias();
    }//GEN-LAST:event_jMenuVolverMouseClicked

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void bLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOutActionPerformed
        /**
         * El botón de LogOut devuelve al usuario a la ventana de LogIn
         */
        this.dispose();
        ControladorVista.mostrarLogin();
    }//GEN-LAST:event_bLogOutActionPerformed

    private void bJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJornadasActionPerformed
        operacionActiva = "jornada";
        try {
            ControladorVista.mostrarVentanaVisualizarJornada();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_bJornadasActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed
    
    
    
    public void showCategorias(){
        bLiga.setVisible(true);
        bJornadas.setVisible(true);
        bEquipos.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEquipos;
    private javax.swing.JButton bJornadas;
    private javax.swing.JButton bLiga;
    private javax.swing.JButton bLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCategoria;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuVolver;
    private javax.swing.JMenuItem miEquipos;
    private javax.swing.JMenuItem miJornadas;
    private javax.swing.JMenuItem miLiga;
    // End of variables declaration//GEN-END:variables
}
