/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.util.ArrayList;
import main.MainEsports;
import modelo.Equipo;
import modelo.Jugador;

/**
 *
 * @author 1gdaw03
 */
public class VentanaVisualizarEquipos extends javax.swing.JFrame {
     private static ArrayList<Equipo> listaEquipos;
     private static ArrayList<Jugador> listaJugadores;
    /**
     * Creates new form VentanaVisualizarEquipos
     */
    public VentanaVisualizarEquipos() throws Exception {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(rootPaneCheckingEnabled);
        setExtendedState(MAXIMIZED_BOTH);
        estiloPaneles();
       listaEquipos = MainEsports.mostrarEquipos();
        llenarFieldsEquipo();
        //listaJugadores = MainEsports.mostrarJugadores();
        llenarFieldsJugador();
        llenarFieldsPresidente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpaco1 = new javax.swing.JPanel();
        tfNombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfJugador1_1 = new javax.swing.JTextField();
        tfJugador2_1 = new javax.swing.JTextField();
        tfJugador3_1 = new javax.swing.JTextField();
        tfJugador4_1 = new javax.swing.JTextField();
        tfJugador5_1 = new javax.swing.JTextField();
        tfJugador6_1 = new javax.swing.JTextField();
        tfPresidente1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelOpaco2 = new javax.swing.JPanel();
        tfNombre2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfJugador1_2 = new javax.swing.JTextField();
        tfJugador2_2 = new javax.swing.JTextField();
        tfJugador3_2 = new javax.swing.JTextField();
        tfJugador5_2 = new javax.swing.JTextField();
        tfJugador4_2 = new javax.swing.JTextField();
        tfJugador6_2 = new javax.swing.JTextField();
        tfPresidente2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelOpaco3 = new javax.swing.JPanel();
        tfNombre3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfJugador1_3 = new javax.swing.JTextField();
        tfJugador2_3 = new javax.swing.JTextField();
        tfJugador3_3 = new javax.swing.JTextField();
        tfJugador5_3 = new javax.swing.JTextField();
        tfJugador4_3 = new javax.swing.JTextField();
        tfJugador6_3 = new javax.swing.JTextField();
        tfPresidente3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        panelOpaco4 = new javax.swing.JPanel();
        tfNombre4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfJugador2_4 = new javax.swing.JTextField();
        tfJugador4_4 = new javax.swing.JTextField();
        tfJugador6_4 = new javax.swing.JTextField();
        tfJugador5_4 = new javax.swing.JTextField();
        tfJugador3_4 = new javax.swing.JTextField();
        tfJugador1_4 = new javax.swing.JTextField();
        tfPresidente4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panelOpaco5 = new javax.swing.JPanel();
        tfNombre5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfJugador2_5 = new javax.swing.JTextField();
        tfJugador4_5 = new javax.swing.JTextField();
        tfJugador6_5 = new javax.swing.JTextField();
        tfJugador5_5 = new javax.swing.JTextField();
        tfJugador3_5 = new javax.swing.JTextField();
        tfJugador1_5 = new javax.swing.JTextField();
        tfPresidente5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        panelOpaco6 = new javax.swing.JPanel();
        tfNombre6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfJugador2_6 = new javax.swing.JTextField();
        tfJugador4_6 = new javax.swing.JTextField();
        tfJugador6_6 = new javax.swing.JTextField();
        tfJugador5_6 = new javax.swing.JTextField();
        tfJugador3_6 = new javax.swing.JTextField();
        tfJugador1_6 = new javax.swing.JTextField();
        tfPresidente6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombre1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jugadores");

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Presidente");

        javax.swing.GroupLayout panelOpaco1Layout = new javax.swing.GroupLayout(panelOpaco1);
        panelOpaco1.setLayout(panelOpaco1Layout);
        panelOpaco1Layout.setHorizontalGroup(
            panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador1_1)
                    .addComponent(tfJugador3_1)
                    .addComponent(tfJugador5_1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador2_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador4_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador6_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(panelOpaco1Layout.createSequentialGroup()
                .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPresidente1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOpaco1Layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelOpaco1Layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpaco1Layout.setVerticalGroup(
            panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelOpaco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador6_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(tfPresidente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(panelOpaco1);
        panelOpaco1.setBounds(100, 50, 400, 400);

        tfNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombre2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jugadores");

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Presidente");

        javax.swing.GroupLayout panelOpaco2Layout = new javax.swing.GroupLayout(panelOpaco2);
        panelOpaco2.setLayout(panelOpaco2Layout);
        panelOpaco2Layout.setHorizontalGroup(
            panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfJugador3_2)
                    .addComponent(tfJugador1_2)
                    .addComponent(tfJugador5_2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador6_2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(tfJugador2_2)
                    .addComponent(tfJugador4_2))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco2Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpaco2Layout.createSequentialGroup()
                        .addComponent(tfNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco2Layout.createSequentialGroup()
                        .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPresidente2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOpaco2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(170, 170, 170))))
        );
        panelOpaco2Layout.setVerticalGroup(
            panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tfNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOpaco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(tfPresidente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        getContentPane().add(panelOpaco2);
        panelOpaco2.setBounds(710, 50, 430, 400);

        tfNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombre3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Jugadores");

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Presidente");

        javax.swing.GroupLayout panelOpaco3Layout = new javax.swing.GroupLayout(panelOpaco3);
        panelOpaco3.setLayout(panelOpaco3Layout);
        panelOpaco3Layout.setHorizontalGroup(
            panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfJugador3_3)
                    .addComponent(tfJugador1_3)
                    .addComponent(tfJugador5_3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador6_3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(tfJugador2_3)
                    .addComponent(tfJugador4_3))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco3Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco3Layout.createSequentialGroup()
                        .addComponent(tfNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco3Layout.createSequentialGroup()
                        .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPresidente3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(162, 162, 162))))
        );
        panelOpaco3Layout.setVerticalGroup(
            panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tfNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOpaco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador5_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador6_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(tfPresidente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelOpaco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(panelOpaco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1360, 50, 420, 400);

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jugadores");

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Presidente");

        javax.swing.GroupLayout panelOpaco4Layout = new javax.swing.GroupLayout(panelOpaco4);
        panelOpaco4.setLayout(panelOpaco4Layout);
        panelOpaco4Layout.setHorizontalGroup(
            panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador1_4)
                    .addComponent(tfJugador3_4)
                    .addComponent(tfJugador5_4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador2_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador4_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador6_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addGroup(panelOpaco4Layout.createSequentialGroup()
                .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOpaco4Layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(tfPresidente4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelOpaco4Layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        panelOpaco4Layout.setVerticalGroup(
            panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tfNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOpaco4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador5_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador6_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(tfPresidente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        getContentPane().add(panelOpaco4);
        panelOpaco4.setBounds(100, 590, 400, 390);

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Jugadores");

        tfJugador2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJugador2_5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Presidente");

        javax.swing.GroupLayout panelOpaco5Layout = new javax.swing.GroupLayout(panelOpaco5);
        panelOpaco5.setLayout(panelOpaco5Layout);
        panelOpaco5Layout.setHorizontalGroup(
            panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador1_5)
                    .addComponent(tfJugador3_5)
                    .addComponent(tfJugador5_5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador2_5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador4_5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador6_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco5Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOpaco5Layout.createSequentialGroup()
                        .addComponent(tfNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco5Layout.createSequentialGroup()
                        .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPresidente5)
                            .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(180, 180, 180))))
        );
        panelOpaco5Layout.setVerticalGroup(
            panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tfNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOpaco5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador5_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador6_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(tfPresidente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        getContentPane().add(panelOpaco5);
        panelOpaco5.setBounds(710, 590, 430, 390);

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jugadores");

        tfJugador2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJugador2_6ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Presidente");

        javax.swing.GroupLayout panelOpaco6Layout = new javax.swing.GroupLayout(panelOpaco6);
        panelOpaco6.setLayout(panelOpaco6Layout);
        panelOpaco6Layout.setHorizontalGroup(
            panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador1_6)
                    .addComponent(tfJugador3_6)
                    .addComponent(tfJugador5_6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfJugador2_6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador4_6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador6_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco6Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco6Layout.createSequentialGroup()
                        .addComponent(tfNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpaco6Layout.createSequentialGroup()
                        .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPresidente6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(167, 167, 167))))
        );
        panelOpaco6Layout.setVerticalGroup(
            panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpaco6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tfNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOpaco6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador5_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador6_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(tfPresidente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        getContentPane().add(panelOpaco6);
        panelOpaco6.setBounds(1360, 590, 420, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Imgs/ImgEquipo/jhin.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1970, 1090);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombre1ActionPerformed

    private void tfNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombre2ActionPerformed

    private void tfNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombre3ActionPerformed

    private void tfJugador2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJugador2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJugador2_5ActionPerformed

    private void tfJugador2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJugador2_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJugador2_6ActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
     
    }//GEN-LAST:event_mSalirActionPerformed

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mSalirMouseClicked
    public  void llenarFieldsEquipo(){
        
    
        tfNombre1.setText(listaEquipos.get(0).getNombre());
        tfNombre2.setText(listaEquipos.get(1).getNombre());
        tfNombre3.setText(listaEquipos.get(2).getNombre());
        tfNombre4.setText(listaEquipos.get(3).getNombre());
        tfNombre5.setText(listaEquipos.get(4).getNombre());
        tfNombre6.setText(listaEquipos.get(5).getNombre());   
    }
    
    public void llenarFieldsJugador(){
        //EQUIPO 1
        tfJugador1_1.setText(listaEquipos.get(0).getListaJugadores().get(0).getNickname().toUpperCase());
        tfJugador2_1.setText(listaEquipos.get(0).getListaJugadores().get(1).getNickname().toUpperCase());
        tfJugador3_1.setText(listaEquipos.get(0).getListaJugadores().get(2).getNickname().toUpperCase());
        if (listaEquipos.get(0).getListaJugadores().size() > 3){
        tfJugador4_1.setText(listaEquipos.get(0).getListaJugadores().get(3).getNickname().toUpperCase());
        tfJugador5_1.setText(listaEquipos.get(0).getListaJugadores().get(4).getNickname().toUpperCase());
        if (listaEquipos.get(0).getListaJugadores().size() == 6){
        tfJugador6_1.setText(listaEquipos.get(0).getListaJugadores().get(5).getNickname().toUpperCase());
        }
        }
        //EQUIPO 2
        tfJugador1_2.setText(listaEquipos.get(1).getListaJugadores().get(0).getNickname().toUpperCase());
        tfJugador2_2.setText(listaEquipos.get(1).getListaJugadores().get(1).getNickname().toUpperCase());
        tfJugador3_2.setText(listaEquipos.get(1).getListaJugadores().get(2).getNickname().toUpperCase());
        if (listaEquipos.get(1).getListaJugadores().size() > 3){
        tfJugador4_2.setText(listaEquipos.get(1).getListaJugadores().get(3).getNickname().toUpperCase());
        tfJugador5_2.setText(listaEquipos.get(1).getListaJugadores().get(4).getNickname().toUpperCase());
        if (listaEquipos.get(1).getListaJugadores().size() == 6){        
        tfJugador6_2.setText(listaEquipos.get(1).getListaJugadores().get(5).getNickname().toUpperCase());
        }
        }
        //EQUIPO 3
        tfJugador1_3.setText(listaEquipos.get(2).getListaJugadores().get(0).getNickname().toUpperCase());
        tfJugador2_3.setText(listaEquipos.get(2).getListaJugadores().get(1).getNickname().toUpperCase());
        tfJugador3_3.setText(listaEquipos.get(2).getListaJugadores().get(2).getNickname().toUpperCase());
        if (listaEquipos.get(2).getListaJugadores().size() > 3){
        tfJugador4_3.setText(listaEquipos.get(2).getListaJugadores().get(3).getNickname().toUpperCase());
        tfJugador5_3.setText(listaEquipos.get(2).getListaJugadores().get(4).getNickname().toUpperCase());
        if (listaEquipos.get(2).getListaJugadores().size() == 6){
        tfJugador6_3.setText(listaEquipos.get(2).getListaJugadores().get(5).getNickname().toUpperCase());
          }
        }
        //EQUIPO 4
        tfJugador1_4.setText(listaEquipos.get(3).getListaJugadores().get(0).getNickname().toUpperCase());
        tfJugador2_4.setText(listaEquipos.get(3).getListaJugadores().get(1).getNickname().toUpperCase());
        tfJugador3_4.setText(listaEquipos.get(3).getListaJugadores().get(2).getNickname().toUpperCase());
        if (listaEquipos.get(3).getListaJugadores().size() > 3){
        tfJugador4_4.setText(listaEquipos.get(3).getListaJugadores().get(3).getNickname().toUpperCase());
        tfJugador5_4.setText(listaEquipos.get(3).getListaJugadores().get(4).getNickname().toUpperCase());
        if (listaEquipos.get(3).getListaJugadores().size() == 6){
        tfJugador6_4.setText(listaEquipos.get(3).getListaJugadores().get(5).getNickname().toUpperCase());
          }
        }
        //EQUIPO 5
        tfJugador1_5.setText(listaEquipos.get(4).getListaJugadores().get(0).getNickname().toUpperCase());
        tfJugador2_5.setText(listaEquipos.get(4).getListaJugadores().get(1).getNickname().toUpperCase());
        tfJugador3_5.setText(listaEquipos.get(4).getListaJugadores().get(2).getNickname().toUpperCase());
        if (listaEquipos.get(4).getListaJugadores().size() > 3){
        tfJugador4_5.setText(listaEquipos.get(4).getListaJugadores().get(3).getNickname().toUpperCase());
        tfJugador5_5.setText(listaEquipos.get(4).getListaJugadores().get(4).getNickname().toUpperCase());
        if (listaEquipos.get(4).getListaJugadores().size() == 6){
        tfJugador6_5.setText(listaEquipos.get(4).getListaJugadores().get(5).getNickname().toUpperCase());
          }
        }
        //EQUIPO 6
        tfJugador1_6.setText(listaEquipos.get(5).getListaJugadores().get(0).getNickname().toUpperCase());
        tfJugador2_6.setText(listaEquipos.get(5).getListaJugadores().get(1).getNickname().toUpperCase());
        tfJugador3_6.setText(listaEquipos.get(5).getListaJugadores().get(2).getNickname().toUpperCase());
           if (listaEquipos.get(5).getListaJugadores().size() > 3){
        tfJugador4_6.setText(listaEquipos.get(5).getListaJugadores().get(3).getNickname().toUpperCase());
        tfJugador5_6.setText(listaEquipos.get(5).getListaJugadores().get(0).getNickname().toUpperCase());
        if (listaEquipos.get(5).getListaJugadores().size() == 6){
        tfJugador6_6.setText(listaEquipos.get(5).getListaJugadores().get(5).getNickname().toUpperCase());
    }}}
    
      public void llenarFieldsPresidente(){
        tfPresidente1.setText(listaEquipos.get(0).getListaPresidentes().get(0).getNombre().toUpperCase());
        tfPresidente1.setText(listaEquipos.get(1).getListaPresidentes().get(1).getNombre().toUpperCase());
        tfPresidente1.setText(listaEquipos.get(2).getListaPresidentes().get(2).getNombre().toUpperCase());
        tfPresidente1.setText(listaEquipos.get(3).getListaPresidentes().get(3).getNombre().toUpperCase());
        tfPresidente1.setText(listaEquipos.get(4).getListaPresidentes().get(4).getNombre().toUpperCase());
        tfPresidente1.setText(listaEquipos.get(5).getListaPresidentes().get(5).getNombre().toUpperCase());   
    }
    
    public void estiloPaneles(){
        panelOpaco1.setBackground(new Color(62, 80, 111,190));
        panelOpaco2.setBackground(new Color(62, 80, 111,190));
        panelOpaco3.setBackground(new Color(62, 80, 111,190));
        panelOpaco4.setBackground(new Color(62, 80, 111,190));
        panelOpaco5.setBackground(new Color(62, 80, 111,190));
        panelOpaco6.setBackground(new Color(62, 80, 111,190));
    }
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu mSalir;
    private javax.swing.JPanel panelOpaco1;
    private javax.swing.JPanel panelOpaco2;
    private javax.swing.JPanel panelOpaco3;
    private javax.swing.JPanel panelOpaco4;
    private javax.swing.JPanel panelOpaco5;
    private javax.swing.JPanel panelOpaco6;
    private javax.swing.JTextField tfJugador1_1;
    private javax.swing.JTextField tfJugador1_2;
    private javax.swing.JTextField tfJugador1_3;
    private javax.swing.JTextField tfJugador1_4;
    private javax.swing.JTextField tfJugador1_5;
    private javax.swing.JTextField tfJugador1_6;
    private javax.swing.JTextField tfJugador2_1;
    private javax.swing.JTextField tfJugador2_2;
    private javax.swing.JTextField tfJugador2_3;
    private javax.swing.JTextField tfJugador2_4;
    private javax.swing.JTextField tfJugador2_5;
    private javax.swing.JTextField tfJugador2_6;
    private javax.swing.JTextField tfJugador3_1;
    private javax.swing.JTextField tfJugador3_2;
    private javax.swing.JTextField tfJugador3_3;
    private javax.swing.JTextField tfJugador3_4;
    private javax.swing.JTextField tfJugador3_5;
    private javax.swing.JTextField tfJugador3_6;
    private javax.swing.JTextField tfJugador4_1;
    private javax.swing.JTextField tfJugador4_2;
    private javax.swing.JTextField tfJugador4_3;
    private javax.swing.JTextField tfJugador4_4;
    private javax.swing.JTextField tfJugador4_5;
    private javax.swing.JTextField tfJugador4_6;
    private javax.swing.JTextField tfJugador5_1;
    private javax.swing.JTextField tfJugador5_2;
    private javax.swing.JTextField tfJugador5_3;
    private javax.swing.JTextField tfJugador5_4;
    private javax.swing.JTextField tfJugador5_5;
    private javax.swing.JTextField tfJugador5_6;
    private javax.swing.JTextField tfJugador6_1;
    private javax.swing.JTextField tfJugador6_2;
    private javax.swing.JTextField tfJugador6_3;
    private javax.swing.JTextField tfJugador6_4;
    private javax.swing.JTextField tfJugador6_5;
    private javax.swing.JTextField tfJugador6_6;
    private javax.swing.JTextField tfNombre1;
    private javax.swing.JTextField tfNombre2;
    private javax.swing.JTextField tfNombre3;
    private javax.swing.JTextField tfNombre4;
    private javax.swing.JTextField tfNombre5;
    private javax.swing.JTextField tfNombre6;
    private javax.swing.JTextField tfPresidente1;
    private javax.swing.JTextField tfPresidente2;
    private javax.swing.JTextField tfPresidente3;
    private javax.swing.JTextField tfPresidente4;
    private javax.swing.JTextField tfPresidente5;
    private javax.swing.JTextField tfPresidente6;
    // End of variables declaration//GEN-END:variables
}
