package vistas;

import java.awt.ComponentOrientation;

/**
 *
 * @author N3Essential
 */
public class VentanaUsuarios extends javax.swing.JFrame {

    
    /**
     * Creates new form VentanaCategoria
     */
    public VentanaUsuarios() {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(rootPaneCheckingEnabled);
        setExtendedState(MAXIMIZED_BOTH);
        
        setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bVisualizarJornadas = new javax.swing.JButton();
        bVisualizarEquipos = new javax.swing.JButton();
        bVisualizarJugadores = new javax.swing.JButton();
        bVisualizarPresidentes = new javax.swing.JButton();
        bVisualizarLiga = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCategoria = new javax.swing.JMenu();
        miVisualizarLiga = new javax.swing.JMenuItem();
        miVisualizarJornadas = new javax.swing.JMenuItem();
        miEquipos = new javax.swing.JMenuItem();
        miJugadores = new javax.swing.JMenuItem();
        miPresidentes = new javax.swing.JMenuItem();
        jMenuCuentas = new javax.swing.JMenu();
        miVisualizarAdministradores = new javax.swing.JMenuItem();
        jMenuVisualizarUsuarios = new javax.swing.JMenu();
        miConsultar = new javax.swing.JMenuItem();
        miEliminar = new javax.swing.JMenuItem();
        jMenuVolverVisualizar = new javax.swing.JMenu();
        jMenuSalirVisualizar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Light", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Mamecorp logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 340, 630, 350));

        bVisualizarJornadas.setBackground(new java.awt.Color(0, 102, 102));
        bVisualizarJornadas.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bVisualizarJornadas.setForeground(new java.awt.Color(255, 255, 255));
        bVisualizarJornadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Jornada.png"))); // NOI18N
        bVisualizarJornadas.setText("   JORNADAS");
        bVisualizarJornadas.setBorder(null);
        bVisualizarJornadas.setBorderPainted(false);
        bVisualizarJornadas.setContentAreaFilled(false);
        bVisualizarJornadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVisualizarJornadas.setFocusPainted(false);
        bVisualizarJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarJornadasActionPerformed(evt);
            }
        });
        getContentPane().add(bVisualizarJornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, 50));

        bVisualizarEquipos.setBackground(new java.awt.Color(0, 102, 102));
        bVisualizarEquipos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bVisualizarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        bVisualizarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Equipo.png"))); // NOI18N
        bVisualizarEquipos.setText("    EQUIPOS");
        bVisualizarEquipos.setBorder(null);
        bVisualizarEquipos.setContentAreaFilled(false);
        bVisualizarEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVisualizarEquipos.setFocusPainted(false);
        bVisualizarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(bVisualizarEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 260, 70));

        bVisualizarJugadores.setBackground(new java.awt.Color(0, 102, 102));
        bVisualizarJugadores.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bVisualizarJugadores.setForeground(new java.awt.Color(255, 255, 255));
        bVisualizarJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/JugadorEsports.png"))); // NOI18N
        bVisualizarJugadores.setText("   JUGADORES");
        bVisualizarJugadores.setBorder(null);
        bVisualizarJugadores.setContentAreaFilled(false);
        bVisualizarJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVisualizarJugadores.setFocusPainted(false);
        bVisualizarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(bVisualizarJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 260, 50));

        bVisualizarPresidentes.setBackground(new java.awt.Color(0, 102, 102));
        bVisualizarPresidentes.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bVisualizarPresidentes.setForeground(new java.awt.Color(255, 255, 255));
        bVisualizarPresidentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Presidentes.png"))); // NOI18N
        bVisualizarPresidentes.setText("  PRESIDENTES");
        bVisualizarPresidentes.setBorder(null);
        bVisualizarPresidentes.setContentAreaFilled(false);
        bVisualizarPresidentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVisualizarPresidentes.setFocusPainted(false);
        bVisualizarPresidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarPresidentesActionPerformed(evt);
            }
        });
        getContentPane().add(bVisualizarPresidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 290, 70));

        bVisualizarLiga.setBackground(new java.awt.Color(255, 255, 255));
        bVisualizarLiga.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bVisualizarLiga.setForeground(new java.awt.Color(255, 255, 255));
        bVisualizarLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/Icono liga.png"))); // NOI18N
        bVisualizarLiga.setText("        LIGA");
        bVisualizarLiga.setBorder(null);
        bVisualizarLiga.setContentAreaFilled(false);
        bVisualizarLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVisualizarLiga.setFocusPainted(false);
        bVisualizarLiga.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bVisualizarLigaMouseMoved(evt);
            }
        });
        bVisualizarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarLigaActionPerformed(evt);
            }
        });
        getContentPane().add(bVisualizarLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 60));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 40, 100, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel3:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1638, 40, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanaCategoria/FondoCategoria.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -630, 3500, 2650));

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenuCategoria.setText("Categoria");

        miVisualizarLiga.setText("Liga");
        miVisualizarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarLigaActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miVisualizarLiga);

        miVisualizarJornadas.setText("Jornadas");
        miVisualizarJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarJornadasActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miVisualizarJornadas);

        miEquipos.setText("Equipos");
        miEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEquiposActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miEquipos);

        miJugadores.setText("Jugadores");
        miJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJugadoresActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miJugadores);

        miPresidentes.setText("Presidentes");
        miPresidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPresidentesActionPerformed(evt);
            }
        });
        jMenuCategoria.add(miPresidentes);

        jMenuBar1.add(jMenuCategoria);

        jMenuCuentas.setText("Cuentas");

        miVisualizarAdministradores.setText("Administradores");
        miVisualizarAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarAdministradoresActionPerformed(evt);
            }
        });
        jMenuCuentas.add(miVisualizarAdministradores);

        jMenuVisualizarUsuarios.setText("Usuarios");

        miConsultar.setText("Consultar");
        jMenuVisualizarUsuarios.add(miConsultar);

        miEliminar.setText("Eliminar");
        jMenuVisualizarUsuarios.add(miEliminar);

        jMenuCuentas.add(jMenuVisualizarUsuarios);

        jMenuBar1.add(jMenuCuentas);

        jMenuVolverVisualizar.setText("Volver");
        jMenuVolverVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVolverVisualizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVolverVisualizar);

        jMenuSalirVisualizar.setText("Salir");
        jMenuSalirVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuSalirVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuSalirVisualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuSalirVisualizar.setInheritsPopupMenu(true);
        jMenuSalirVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirVisualizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalirVisualizar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVisualizarJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarJornadasActionPerformed
        ocultarBotonesYMostrarCrud();
    }//GEN-LAST:event_bVisualizarJornadasActionPerformed

    private void bVisualizarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarEquiposActionPerformed
       ocultarBotonesYMostrarCrud();
    }//GEN-LAST:event_bVisualizarEquiposActionPerformed

    private void bVisualizarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarJugadoresActionPerformed
        ocultarBotonesYMostrarCrud();
    }//GEN-LAST:event_bVisualizarJugadoresActionPerformed

    private void jMenuSalirVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirVisualizarMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jMenuSalirVisualizarMouseClicked

    private void miVisualizarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarLigaActionPerformed
        bVisualizarLiga.doClick();
    }//GEN-LAST:event_miVisualizarLigaActionPerformed

    private void miVisualizarJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarJornadasActionPerformed
        bVisualizarJornadas.doClick();
    }//GEN-LAST:event_miVisualizarJornadasActionPerformed

    private void bVisualizarPresidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarPresidentesActionPerformed
        ocultarBotonesYMostrarCrud();
    }//GEN-LAST:event_bVisualizarPresidentesActionPerformed

    private void miEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEquiposActionPerformed
        bVisualizarEquipos.doClick();
    }//GEN-LAST:event_miEquiposActionPerformed

    private void bVisualizarLigaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVisualizarLigaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_bVisualizarLigaMouseMoved

    private void bVisualizarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarLigaActionPerformed
        ocultarBotonesYMostrarCrud();
    }//GEN-LAST:event_bVisualizarLigaActionPerformed

    private void jMenuVolverVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVolverVisualizarMouseClicked
     
        showCategorias();
    }//GEN-LAST:event_jMenuVolverVisualizarMouseClicked

    private void miJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJugadoresActionPerformed
        bVisualizarJugadores.doClick();
    }//GEN-LAST:event_miJugadoresActionPerformed

    private void miPresidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPresidentesActionPerformed
        bVisualizarPresidentes.doClick();
    }//GEN-LAST:event_miPresidentesActionPerformed

    private void miVisualizarAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarAdministradoresActionPerformed
        ocultarBotonesYMostrarCrud();
    }//GEN-LAST:event_miVisualizarAdministradoresActionPerformed
    
   
    
    public void ocultarBotonesYMostrarCrud(){
      
        
        bVisualizarLiga.setVisible(false);
        bVisualizarJornadas.setVisible(false);
       
        bVisualizarEquipos.setVisible(false);
        bVisualizarJugadores.setVisible(false);
        bVisualizarPresidentes.setVisible(false);
    }
    
    public void showCategorias(){
        bVisualizarLiga.setVisible(true);
        bVisualizarJornadas.setVisible(true);
      
        bVisualizarEquipos.setVisible(true);
        bVisualizarJugadores.setVisible(true);
        bVisualizarPresidentes.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bVisualizarEquipos;
    private javax.swing.JButton bVisualizarJornadas;
    private javax.swing.JButton bVisualizarJugadores;
    private javax.swing.JButton bVisualizarLiga;
    private javax.swing.JButton bVisualizarPresidentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCategoria;
    private javax.swing.JMenu jMenuCuentas;
    private javax.swing.JMenu jMenuSalirVisualizar;
    private javax.swing.JMenu jMenuVisualizarUsuarios;
    private javax.swing.JMenu jMenuVolverVisualizar;
    private javax.swing.JMenuItem miConsultar;
    private javax.swing.JMenuItem miEliminar;
    private javax.swing.JMenuItem miEquipos;
    private javax.swing.JMenuItem miJugadores;
    private javax.swing.JMenuItem miPresidentes;
    private javax.swing.JMenuItem miVisualizarAdministradores;
    private javax.swing.JMenuItem miVisualizarJornadas;
    private javax.swing.JMenuItem miVisualizarLiga;
    // End of variables declaration//GEN-END:variables
}
