CREATE OR REPLACE FUNCTION FUNCTION_COUNT_JUG_EQUIPO 
(ID_EQUIPO IN EQUIPO.ID_EQUIPO%TYPE)
RETURN NUMBER
AS
NUM_JUGADORES NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM_JUGADORES 
    FROM JUGADOR
    WHERE Equipo_id_equipo = id_equipo;
RETURN(NUM_JUGADORES );
END FUNCTION_COUNT_JUG_EQUIPO;

--LLAMADA A LA FUNCION
DECLARE
jugadores_msg NUMBER(2);
BEGIN
    jugadores_msg := FUNCTION_COUNT_JUG_EQUIPO(6);
    DBMS_OUTPUT.PUT_LINE(jugadores_msg);
END;